"""Create first migration

Revision ID: ec155d88ca7d
Revises: 567c46fae12b
Create Date: 2024-08-22 21:21:22.657947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec155d88ca7d'
down_revision = '567c46fae12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
